bayesianOptimization:
  dev:
    init_points: 4
    n_iter: 8
    acq: 'ucb'
  prod:
    init_points: 16
    n_iter: 48
    acq: 'ucb'

pbounds:
  lightgbm:
    reg_alpha: (0.1, 10)
    reg_lambda: (0.1, 10)
    learning_rate: (0.01, 0.1)
    min_child_samples: (2, 10)
    num_leaves: (15, 100)
    k: (80,512)
  logistic_regression:
    C: (0.0001, 1)
    l1_ratio: (0.0001, 1)
    k: (80,512)
  xgboost:
    reg_alpha: (0.1, 10)
    reg_lambda: (0.1, 10)
    learning_rate: (0.01, 0.1)
    min_child_weight: (0, 5)
    max_leaves: (15, 100)
    k: (80,512)
  randomforest:
    n_estimators: (50, 100)
    max_depth: (1, 5)
    min_samples_split: (2, 10)
    min_samples_leaf: (1, 10)
    k: (80,512)
  svc:
    C: (0.0001, 1)
    k: (80,512)

features_configuration:
  A:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'new_currency_code']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price']

  B:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'new_currency_code', 'season', 'platform', 'check_in_month','holiday','weekday']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment',  'lead_time']

  C:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'new_currency_code','important_sp_date','create_is_weekday']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'stay_night_is_national_holiday','stay_night_is_holiday','stay_night_is_weekday']

  D:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'new_currency_code', 'season', 'platform', 'check_in_month','holiday','weekday','important_sp_date','create_is_weekday']
    numerical: ['number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment',  'lead_time', 'stay_night_is_national_holiday','stay_night_is_holiday','stay_night_is_weekday']

  Z:
    onehot: ['payment_type', 'nationality_code', 'gender', 'source', 'new_currency_code', 'season', 'platform', 'check_in_month','holiday','weekday','important_sp_date','create_is_weekday',
              '所在縣市', '旅店類型']
    numerical: [ 'number_of_allpeople', 'total_stays_night', 'tax_rate', 'service_rate', 'price', 'if_comment', 'lead_time', 'stay_night_is_national_holiday', 'stay_night_is_holiday','stay_night_is_weekday', '房間數']